package com.example.proyecto

fun obtenerConsejoAzar(): String {
    val consejos = listOf(
        "Busca apoyo en amigos y familiares.",
        "Evita situaciones que te generen ganas de fumar.",
        "Toma agua cuando tengas ansiedad.",
        "Haz ejercicio para liberar estrés.",
        "Recuérdate por qué decidiste dejar de fumar.",
        "Mastica chicle o come algo saludable.",
        "Evita el alcohol y la cafeína en los primeros días.",
        "Celebra tus logros sin cigarro.",
        "Haz una lista de beneficios al dejar de fumar.",
        "Ahorra el dinero que gastabas en cigarrillos.",
        "Cambia tu rutina diaria para evitar tentaciones.",
        "Respira profundamente cuando sientas ansiedad.",
        "Habla con alguien de confianza cuando tengas recaídas.",
        "Usa aplicaciones para seguir tu progreso.",
        "Evita estar con personas que fuman al principio.",
        "Haz un calendario con tus metas.",
        "Concédele a tu cuerpo el descanso que necesita.",
        "Limpia objetos que huelan a cigarro.",
        "Come frutas y verduras para sentirte mejor.",
        "Recompénsate con algo especial cada semana sin fumar.",
        "Cambia el café por té durante los primeros días.",
        "No lleves encendedores ni cigarrillos contigo.",
        "Haz actividades manuales para mantener las manos ocupadas.",
        "Recuerda que cada día sin fumar es un logro.",
        "Escribe un diario con tu progreso.",
        "Mantén una actitud positiva, aunque recaigas.",
        "Visualiza cómo te sentirás libre del cigarro.",
        "Evita lugares donde solías fumar.",
        "Conecta con otros que también están dejando de fumar.",
        "Utiliza técnicas de relajación como yoga o meditación.",
        "Haz pequeños retos diarios y cúmplelos.",
        "Pon mensajes motivacionales en tu habitación.",
        "No compres paquetes 'por si acaso'.",
        "Cuenta tus logros a los demás para motivarte.",
        "Aprende sobre los daños del tabaco para reforzar tu decisión.",
        "Acepta que es difícil, pero no imposible.",
        "Disfruta de tu respiración limpia y profunda.",
        "Consulta a un profesional si lo necesitas.",
        "Evita comidas muy pesadas que te hagan querer fumar.",
        "Ocupa tu mente leyendo o viendo películas.",
        "Lleva un registro de cuánto dinero ahorras.",
        "Comparte tu progreso en redes sociales.",
        "Crea un plan para los momentos difíciles.",
        "Recuerda que el primer día es el más difícil.",
        "Reemplaza el cigarro con hábitos saludables.",
        "Descansa lo suficiente: el cansancio puede aumentar la ansiedad.",
        "Permítete sentir emociones sin recurrir al cigarro.",
        "Recuérdate que mereces una vida sana.",
        "Haz de esto tu prioridad personal.",
        "No te castigues por una recaída, vuelve a intentarlo."
    )

    return consejos.random()
}
